---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: smart-home
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Services for managing and automating the home
  destinations:
    - namespace: home-assistant
      server: https://kubernetes.default.svc
    - namespace: mosquitto
      server: https://kubernetes.default.svc
    - namespace: node-red
      server: https://kubernetes.default.svc
    - namespace: unifi
      server: https://kubernetes.default.svc
    - namespace: zigbee2mqtt
      server: https://kubernetes.default.svc
    - namespace: ddns
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
