---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-haproxy
  namespace: monitoring
spec:
  endpoints:
    - interval: 3s
      path: /metrics
      targetPort: stat
  namespaceSelector:
    matchNames:
      - haproxy-ingress
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: haproxy-ingress
