---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: haproxy-ingress
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
